# Generated by Django 4.2.20 on 2025-05-13 06:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('power', models.FloatField(default=0)),
                ('torque', models.FloatField(default=0)),
                ('top_speed', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('length', models.FloatField(default=0)),
                ('country', models.CharField(max_length=255)),
                ('turn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('weather', models.CharField(default='', max_length=255)),
                ('session_type', models.CharField(default='Started', max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simracing.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simracing.driver')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simracing.track')),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.FloatField(default=0)),
                ('date', models.DateField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('comments', models.TextField()),
                ('fuel', models.IntegerField(default=0)),
                ('tyre_pressure_fr', models.FloatField(default=0)),
                ('tyre_pressure_fl', models.FloatField(default=0)),
                ('tyre_pressure_rr', models.FloatField(default=0)),
                ('tyre_pressure_rl', models.FloatField(default=0)),
                ('tyre_temperature_fr', models.IntegerField(default=0)),
                ('tyre_temperature_fl', models.IntegerField(default=0)),
                ('tyre_temperature_rr', models.IntegerField(default=0)),
                ('tyre_temperature_rl', models.IntegerField(default=0)),
                ('usure_plaquette', models.FloatField(default=0)),
                ('lap_type', models.CharField(default='Completed', max_length=255)),
                ('lap_index_session', models.IntegerField(default=1)),
                ('lap_index_tyre', models.IntegerField(default=1)),
                ('sector1', models.IntegerField(default=0)),
                ('sector2', models.IntegerField(default=0)),
                ('sector3', models.IntegerField(default=0)),
                ('tc_level', models.IntegerField(default=0)),
                ('abs_level', models.IntegerField(default=0)),
                ('valid_lap', models.BooleanField(default=True)),
                ('tyre_set', models.IntegerField(default=0)),
                ('telemetry_file', models.FileField(blank=True, null=True, upload_to='telemetry_files/')),
                ('lap_beacons', models.JSONField(default=dict)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simracing.compound')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simracing.session')),
            ],
        ),
    ]
