# Generated by Django 4.2.20 on 2025-05-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simracing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lap',
            name='lap_beacons',
        ),
    ]
