# Generated by Django 4.2.20 on 2025-05-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simracing', '0003_lap_lap_beacons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lap',
            name='lap_beacons',
        ),
        migrations.AddField(
            model_name='track',
            name='lap_beacons',
            field=models.JSONField(default=dict),
        ),
    ]
