# Generated by Django 4.2.20 on 2025-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simracing', '0004_remove_lap_lap_beacons_track_lap_beacons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lap',
            old_name='temperature',
            new_name='air_temp',
        ),
        migrations.AddField(
            model_name='lap',
            name='engine_map',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lap',
            name='road_temp',
            field=models.FloatField(default=0),
        ),
    ]
