# Generated by Django 4.2.20 on 2025-07-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simracing', '0005_rename_temperature_lap_air_temp_lap_engine_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
